version: '3.8'

services:
  wbm1:
    build: ./broker-manager
    command: python main.py wmd1
    volumes:
      - ./broker-manager:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - wmd1
  
  wmd1:
    image: postgres:13-alpine
    volumes:
      - md1:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=admin
  
  rbm1:
    build: ./broker-manager
    command: python read.py rmd1
    volumes:
      - ./broker-manager:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - rmd1
  
  rmd1:
    image: postgres:13-alpine
    volumes:
      - md1:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=admin
  
  b1:
    build: ./broker
    command: python main.py db1 wbm1 1
    volumes:
      - ./broker:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db1
  
  db1:
    image: postgres:13-alpine
    volumes:
      - db1:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=admin


volumes:
  wmd1:
  rmd1:
  db1: