version: '3.8'

services:
  wbm1:
    build: ./broker-manager
    command: python main.py md1
    volumes:
      - ./broker-manager:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - md1
  
  md1:
    image: postgres:13-alpine
    volumes:
      - md1:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=admin
  
  
  b1:
    build: ./broker
    command: python main.py db1 wbm1 1
    volumes:
      - ./broker:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db1
  
  db1:
    image: postgres:13-alpine
    volumes:
      - db1:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=admin


volumes:
  md1:
  db1: